### ISSUE TITLE
saving game resolution to player prefs

### ISSUE THREAD

**Issue by ghost** [AIRTV-GH/Draxis#1]
for now we are getting the screen resolution at intro scene.
probably this will work only for this scene , we need to save the resolution to playerprefs , so we can access the game's resolution from other scenes whenever we need that.

here is some hint for player prefs : https://docs.unity3d.com/ScriptReference/PlayerPrefs.html

**Comment by Cstough** [comment]
I think I did this correctly, seems to work.
